services:
  - type: web
    name: sf-order-system
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "false"
      - key: PYTHON_VERSION
        value: "3.11.9"
